version: '3.8'
services:
  angularfileshare:
    container_name: FSContainer
    build: ./
    volumes:
      - "/.FSDocker:/src/app:ro"
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    
